// src/App.vue
﻿<script setup>
import { computed, ref } from 'vue'
import Login from './components/Login.vue'
import Register from './components/Register.vue'
import Home from './components/Home.vue'

const username = ref('')
const password = ref('')
const showPassword = ref(false)
const loading = ref(false)
const error = ref('')
const status = ref('')
const view = ref('login')

const registerUsername = ref('')
const registerPassword = ref('')
const registerConfirmPassword = ref('')
const registerLoading = ref(false)
const registerError = ref('')
const registerStatus = ref('')

const apiBase = import.meta.env.VITE_API_BASE || 'http://192.168.0.6:3001'
const token = ref(localStorage.getItem('xinchat.token') || '')
const profile = ref(
  JSON.parse(localStorage.getItem('xinchat.profile') || 'null') || {}
)

const canSubmit = computed(() => username.value.trim() && password.value)
const canRegister = computed(() => {
  const nameOk = registerUsername.value.trim().length > 0
  const pwdOk = registerPassword.value.length > 0
  const confirmOk =
    registerConfirmPassword.value.length > 0 &&
    registerConfirmPassword.value === registerPassword.value
  return nameOk && pwdOk && confirmOk
})
const isAuthed = computed(() => Boolean(token.value))


const setAuthSession = (data) => {
  localStorage.setItem('xinchat.token', data.token || '')
  localStorage.setItem(
    'xinchat.profile',
    JSON.stringify({
      uid: data.uid,
      username: data.username,
      nickname: data.nickname,
      avatar: data.avatar,
      signature: data.signature,
      gender: data.gender,
      birthday: data.birthday,
      country: data.country,
      province: data.province,
      region: data.region,
      tokenExpiresAt: data.tokenExpiresAt,
    })
  )

  token.value = data.token || ''
  profile.value = {
    uid: data.uid,
    username: data.username,
    nickname: data.nickname,
    avatar: data.avatar,
    signature: data.signature,
  }
}

const submit = async () => {
  error.value = ''
  status.value = ''

  if (!canSubmit.value) {
    error.value = '请输入昵称和密码。'
    return
  }

  loading.value = true
  try {
    const response = await fetch(`${apiBase}/api/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        username: username.value.trim(),
        password: password.value,
      }),
    })

    const data = await response.json().catch(() => ({}))
    if (!response.ok || !data?.success) {
      error.value = data?.message || '登录失败，请重试。'
      return
    }

    setAuthSession(data)
    status.value = data?.message || '登录成功。'
  } catch (err) {
    error.value = '网络错误，请检查服务器后重试。'
  } finally {
    loading.value = false
  }
}

const logout = () => {
  localStorage.removeItem('xinchat.token')
  localStorage.removeItem('xinchat.profile')
  token.value = ''
  profile.value = {}
}

const goRegister = () => {
  registerError.value = ''
  registerStatus.value = ''
  registerConfirmPassword.value = ''
  view.value = 'register'
}

const goLogin = () => {
  error.value = ''
  status.value = ''
  view.value = 'login'
}

const register = async () => {
  registerError.value = ''
  registerStatus.value = ''

  if (!canRegister.value) {
    if (!registerUsername.value.trim() || !registerPassword.value) {
      registerError.value = '请输入昵称和密码。'
    } else if (registerConfirmPassword.value !== registerPassword.value) {
      registerError.value = '两次输入的密码不一致。'
    } else {
      registerError.value = '请确认密码。'
    }
    return
  }

  registerLoading.value = true
  try {
    const response = await fetch(`${apiBase}/api/register`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        username: registerUsername.value.trim(),
        password: registerPassword.value,
      }),
    })

    const data = await response.json().catch(() => ({}))
    if (!response.ok || !data?.success) {
      registerError.value = data?.message || '注册失败，请重试。'
      return
    }

    registerStatus.value = data?.message || '注册成功。'

    const loginResponse = await fetch(`${apiBase}/api/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        username: registerUsername.value.trim(),
        password: registerPassword.value,
      }),
    })

    const loginData = await loginResponse.json().catch(() => ({}))
    if (!loginResponse.ok || !loginData?.success) {
      registerError.value = loginData?.message || '自动登录失败，请手动登录。'
      return
    }

    setAuthSession(loginData)
    view.value = 'login'
    registerConfirmPassword.value = ''
    registerConfirmPassword.value = ''
  } catch (err) {
    registerError.value = '网络错误，请检查服务器后重试。'
  } finally {
    registerLoading.value = false
  }
}
</script>

<template>
  <div class="page" v-cloak>
    <Login
      v-if="!isAuthed && view === 'login'"
      v-model:username="username"
      v-model:password="password"
      :show-password="showPassword"
      :loading="loading"
      :error="error"
      :status="status"
      :can-submit="canSubmit"
      @submit="submit"
      @toggle-password="showPassword = !showPassword"
      @go-register="goRegister"
    />
    <Register
      v-else-if="!isAuthed && view === 'register'"
      v-model:username="registerUsername"
      v-model:password="registerPassword"
      v-model:confirmPassword="registerConfirmPassword"
      :loading="registerLoading"
      :error="registerError"
      :status="registerStatus"
      :can-submit="canRegister"
      @submit="register"
      @back="goLogin"
    />
    <Home v-else :profile="profile" @logout="logout" />
  </div>
</template>

<style scoped>
.page {
  min-height: 100vh;
  background: #f2f3f5;
}

</style>

// App.tsx
import { useEffect, useMemo, useState } from 'react';
import { StatusBar } from 'react-native';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import Home from './src/components/Home';
import Login from './src/components/Login';
import Register from './src/components/Register';
import { API_BASE } from './src/config';
import { storage } from './src/storage';

const TOKEN_KEY = 'xinchat.token';
const PROFILE_KEY = 'xinchat.profile';

type Profile = {
  uid?: number;
  username?: string;
  nickname?: string;
  avatar?: string;
  signature?: string;
  gender?: string;
  birthday?: string;
  country?: string;
  province?: string;
  region?: string;
  tokenExpiresAt?: string | number;
};

const emptyProfile: Profile = {};

function App() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [status, setStatus] = useState('');
  const [view, setView] = useState<'login' | 'register'>('login');

  const [registerUsername, setRegisterUsername] = useState('');
  const [registerPassword, setRegisterPassword] = useState('');
  const [registerConfirmPassword, setRegisterConfirmPassword] = useState('');
  const [registerLoading, setRegisterLoading] = useState(false);
  const [registerError, setRegisterError] = useState('');
  const [registerStatus, setRegisterStatus] = useState('');

  const [token, setToken] = useState('');
  const [profile, setProfile] = useState<Profile>(emptyProfile);

  const canSubmit = useMemo(() => username.trim().length > 0 && password.length > 0, [
    username,
    password,
  ]);
  const canRegister = useMemo(() => {
    const nameOk = registerUsername.trim().length > 0;
    const pwdOk = registerPassword.length > 0;
    const confirmOk =
      registerConfirmPassword.length > 0 && registerConfirmPassword === registerPassword;
    return nameOk && pwdOk && confirmOk;
  }, [registerUsername, registerPassword, registerConfirmPassword]);
  const isAuthed = useMemo(() => Boolean(token), [token]);

  useEffect(() => {
    const loadSession = async () => {
      const storedToken = (await storage.getString(TOKEN_KEY)) || '';
      const storedProfile = (await storage.getJson<Profile>(PROFILE_KEY)) || emptyProfile;
      setToken(storedToken);
      setProfile(storedProfile);
    };
    void loadSession();
  }, []);

  const setAuthSession = async (data: Profile & { token?: string }) => {
    const nextToken = data.token || '';
    const nextProfile: Profile = {
      uid: data.uid,
      username: data.username,
      nickname: data.nickname,
      avatar: data.avatar,
      signature: data.signature,
      gender: data.gender,
      birthday: data.birthday,
      country: data.country,
      province: data.province,
      region: data.region,
      tokenExpiresAt: data.tokenExpiresAt,
    };
    await storage.setString(TOKEN_KEY, nextToken);
    await storage.setJson(PROFILE_KEY, nextProfile);
    setToken(nextToken);
    setProfile(nextProfile);
  };

  const submit = async () => {
    setError('');
    setStatus('');

    if (!canSubmit) {
      setError('Please enter username and password.');
      return;
    }

    setLoading(true);
    try {
      const response = await fetch(API_BASE + '/api/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          username: username.trim(),
          password,
        }),
      });

      const data = await response.json().catch(() => ({}));
      if (!response.ok || !data?.success) {
        setError(data?.message || 'Login failed. Please try again.');
        return;
      }

      await setAuthSession(data);
      setStatus(data?.message || 'Login successful.');
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn('Login request failed', { base: API_BASE, error: message });
      setError('Network error: ' + message);
    } finally {
      setLoading(false);
    }
  };

  const goRegister = () => {
    setRegisterError('');
    setRegisterStatus('');
    setRegisterConfirmPassword('');
    setView('register');
  };

  const goLogin = () => {
    setError('');
    setStatus('');
    setView('login');
  };

  const register = async () => {
    setRegisterError('');
    setRegisterStatus('');

    if (!canRegister) {
      if (!registerUsername.trim() || !registerPassword) {
        setRegisterError('Please enter username and password.');
      } else if (registerConfirmPassword !== registerPassword) {
        setRegisterError('Passwords do not match.');
      } else {
        setRegisterError('Please confirm password.');
      }
      return;
    }

    setRegisterLoading(true);
    try {
      const response = await fetch(API_BASE + '/api/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          username: registerUsername.trim(),
          password: registerPassword,
        }),
      });

      const data = await response.json().catch(() => ({}));
      if (!response.ok || !data?.success) {
        setRegisterError(data?.message || 'Register failed. Please try again.');
        return;
      }

      setRegisterStatus(data?.message || 'Register successful.');

      const loginResponse = await fetch(API_BASE + '/api/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          username: registerUsername.trim(),
          password: registerPassword,
        }),
      });

      const loginData = await loginResponse.json().catch(() => ({}));
      if (!loginResponse.ok || !loginData?.success) {
        setRegisterError(loginData?.message || 'Auto login failed. Please login manually.');
        return;
      }

      await setAuthSession(loginData);
      setView('login');
      setRegisterConfirmPassword('');
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn('Register request failed', { base: API_BASE, error: message });
      setRegisterError('Network error: ' + message);
    } finally {
      setRegisterLoading(false);
    }
  };

  return (
    <SafeAreaProvider>
      <StatusBar barStyle={'dark-content'} />
      {!isAuthed && view === 'login' ? (
        <Login
          username={username}
          password={password}
          showPassword={showPassword}
          loading={loading}
          error={error}
          status={status}
          canSubmit={canSubmit}
          onUsernameChange={setUsername}
          onPasswordChange={setPassword}
          onTogglePassword={() => setShowPassword((prev) => !prev)}
          onSubmit={submit}
          onGoRegister={goRegister}
        />
      ) : null}
      {!isAuthed && view === 'register' ? (
        <Register
          username={registerUsername}
          password={registerPassword}
          confirmPassword={registerConfirmPassword}
          loading={registerLoading}
          error={registerError}
          status={registerStatus}
          canSubmit={canRegister}
          onUsernameChange={setRegisterUsername}
          onPasswordChange={setRegisterPassword}
          onConfirmPasswordChange={setRegisterConfirmPassword}
          onSubmit={register}
          onBack={goLogin}
        />
      ) : null}
      {isAuthed ? <Home profile={profile} /> : null}
    </SafeAreaProvider>
  );
}

export default App;
