// src/components/Login.vue
﻿<script setup>
const props = defineProps({
  username: {
    type: String,
    default: '',
  },
  password: {
    type: String,
    default: '',
  },
  showPassword: {
    type: Boolean,
    default: false,
  },
  loading: {
    type: Boolean,
    default: false,
  },
  error: {
    type: String,
    default: '',
  },
  status: {
    type: String,
    default: '',
  },
  canSubmit: {
    type: Boolean,
    default: false,
  },
})

const emit = defineEmits([
  'update:username',
  'update:password',
  'toggle-password',
  'submit',
  'go-register',
])
</script>

<template>
  <div class="login-qq">
    <header class="header">
      <svg
        class="back-icon"
        viewBox="0 0 24 24"
        fill="none"
        stroke="#000"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <polyline points="15 18 9 12 15 6"></polyline>
      </svg>
    </header>

    <div class="title-area">
      <h1>添加账号</h1>
    </div>

    <form class="form-container" @submit.prevent="emit('submit')">
      <div class="input-group">
        <input
          :value="props.username"
          type="text"
          name="username"
          autocomplete="username"
          placeholder="输入昵称"
          @input="emit('update:username', $event.target.value)"
        />
      </div>

      <div class="input-group">
        <input
          :value="props.password"
          :type="props.showPassword ? 'text' : 'password'"
          name="password"
          autocomplete="current-password"
          placeholder="输入信聊密码"
          @input="emit('update:password', $event.target.value)"
        />
      </div>

      <button class="login-btn" type="submit" :disabled="!props.canSubmit || props.loading">
        {{ props.loading ? '登录中...' : '登录' }}
      </button>

      <p v-if="props.error" class="message error">{{ props.error }}</p>
      <p v-else-if="props.status" class="message success">{{ props.status }}</p>

      <label class="agreement">
        <input class="agreement-input" type="checkbox" checked />
        <span class="checkbox-custom"></span>
        <span>
          已阅读并同意
          <a href="#">服务协议</a>
          和
          <a href="#">信聊隐私保护指引</a>
        </span>
      </label>
    </form>

    <nav class="bottom-nav">
      <button class="nav-item nav-button" type="button" @click="emit('go-register')">
        <div class="icon-circle">
          <svg
            class="icon-svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <line x1="12" y1="5" x2="12" y2="19"></line>
            <line x1="5" y1="12" x2="19" y2="12"></line>
          </svg>
        </div>
        <span>注册</span>
      </button>
    </nav>

    <footer class="footer">Copyright © 2025-2026 WebClass All Rights Reserved.</footer>
  </div>
</template>

<style scoped>
.login-qq {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.header {
  padding: 15px 20px;
  height: 50px;
  display: flex;
  align-items: center;
}

.back-icon {
  width: 24px;
  height: 24px;
  cursor: pointer;
}

.title-area {
  margin-top: 40px;
  margin-bottom: 40px;
  text-align: center;
}

.title-area h1 {
  font-size: 24px;
  font-weight: 500;
  color: #1a1a1a;
  letter-spacing: 1px;
}

.form-container {
  padding: 0 30px;
  display: flex;
  flex-direction: column;
  gap: 15px;
}

.input-group {
  background: #ffffff;
  border-radius: 12px;
  height: 55px;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.02);
}

.input-group input {
  width: 100%;
  height: 100%;
  border: none;
  outline: none;
  background: transparent;
  text-align: center;
  font-size: 16px;
  color: #333;
}

.input-group input::placeholder {
  color: #c0c4cc;
}

.login-btn {
  margin-top: 30px;
  height: 50px;
  background-color: #4a9df8;
  color: white;
  border: none;
  border-radius: 10px;
  font-size: 17px;
  font-weight: 500;
  letter-spacing: 1px;
  cursor: pointer;
  width: 100%;
}

.login-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.login-btn:active {
  background-color: #3b8cd6;
}

.agreement {
  margin-top: 20px;
  display: flex;
  align-items: flex-start;
  justify-content: center;
  font-size: 12px;
  color: #888;
  line-height: 1.5;
  gap: 6px;
}

.agreement-input {
  position: absolute;
  opacity: 0;
  pointer-events: none;
}

.checkbox-custom {
  width: 16px;
  height: 16px;
  border: 1px solid #ccc;
  border-radius: 50%;
  margin-top: 1px;
  position: relative;
  flex-shrink: 0;
}

.agreement-input:checked + .checkbox-custom {
  border-color: #4a9df8;
  background: #4a9df8;
}

.agreement-input:checked + .checkbox-custom::after {
  content: '';
  position: absolute;
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: #fff;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.agreement a {
  color: #5d6b85;
  text-decoration: none;
}

.bottom-nav {
  margin-top: auto;
  padding-bottom: 40px;
  display: flex;
  justify-content: center;
  padding-left: 20px;
  padding-right: 20px;
}

.nav-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  color: #666;
  font-size: 12px;
}

.nav-button {
  background: none;
  border: none;
  padding: 0;
  cursor: pointer;
}

.icon-circle {
  width: 48px;
  height: 48px;
  background: #ffffff;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 1px solid #e5e5e5;
  color: #333;
}

.icon-svg {
  width: 24px;
  height: 24px;
  fill: #333;
}

.message {
  font-size: 0.9rem;
  margin: 0;
}

.error {
  color: #b5482b;
}

.success {
  color: #2f6bd9;
}

.footer {
  margin-bottom: 20px;
  text-align: center;
  font-size: 11px;
  color: #999;
  width: 100%;
  padding: 0 20px;
  line-height: 1.5;
}
</style>

// src/components/Login.tsx
import React from 'react';
import {
  ActivityIndicator,
  Pressable,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Svg, { Circle, Line, Path } from 'react-native-svg';

type Props = {
  username: string;
  password: string;
  showPassword: boolean;
  loading: boolean;
  error: string;
  status: string;
  canSubmit: boolean;
  onUsernameChange: (value: string) => void;
  onPasswordChange: (value: string) => void;
  onTogglePassword: () => void;
  onSubmit: () => void;
  onGoRegister: () => void;
};

export default function Login({
  username,
  password,
  showPassword,
  loading,
  error,
  status,
  canSubmit,
  onUsernameChange,
  onPasswordChange,
  onTogglePassword,
  onSubmit,
  onGoRegister,
}: Props) {
  const insets = useSafeAreaInsets();

  return (
    <View
      style={[
        styles.page,
        { paddingTop: insets.top + 40, paddingBottom: 30 + insets.bottom },
      ]}
    >
      <View style={styles.titleArea}>
        <Text style={styles.title}>添加账号</Text>
      </View>

      <View style={styles.form}>
        <View style={styles.inputGroup}>
          <TextInput
            value={username}
            placeholder="输入昵称"
            placeholderTextColor="#c0c4cc"
            onChangeText={onUsernameChange}
            style={styles.input}
            autoCapitalize="none"
          />
        </View>

        <View style={styles.inputGroup}>
          <TextInput
            value={password}
            placeholder="输入信聊密码"
            placeholderTextColor="#c0c4cc"
            onChangeText={onPasswordChange}
            style={styles.input}
            autoCapitalize="none"
            secureTextEntry={!showPassword}
          />
          <Pressable onPress={onTogglePassword} style={styles.iconButton} hitSlop={8}>
            {showPassword ? <EyeOpenIcon /> : <EyeClosedIcon />}
          </Pressable>
        </View>

        <Pressable
          style={[styles.loginBtn, (!canSubmit || loading) && styles.loginBtnDisabled]}
          disabled={!canSubmit || loading}
          onPress={onSubmit}
        >
          {loading ? (
            <ActivityIndicator color="#fff" />
          ) : (
            <Text style={styles.loginBtnText}>登录</Text>
          )}
        </Pressable>

        {error ? <Text style={styles.error}>{error}</Text> : null}
        {!error && status ? <Text style={styles.success}>{status}</Text> : null}
      </View>

      <View style={styles.footer}>
        <Pressable style={styles.registerBtn} onPress={onGoRegister}>
          <RegisterPlusIcon />
        </Pressable>
        <Text style={styles.copyright}>Copyright © 2025-2026 WebClass</Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#f2f3f5',
    paddingHorizontal: 24,
  },
  titleArea: {
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 40,
  },
  title: {
    fontSize: 24,
    fontWeight: '600',
    color: '#1a1a1a',
    letterSpacing: 1,
  },
  form: {
    gap: 16,
  },
  inputGroup: {
    backgroundColor: '#fff',
    borderRadius: 12,
    height: 54,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 1,
    position: 'relative',
  },
  input: {
    flex: 1,
    width: '100%',
    fontSize: 16,
    color: '#333',
    textAlign: 'center',
    paddingHorizontal: 36,
  },
  iconButton: {
    position: 'absolute',
    right: 14,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  loginBtn: {
    marginTop: 20,
    height: 50,
    borderRadius: 12,
    backgroundColor: '#4a9df8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginBtnDisabled: {
    opacity: 0.6,
  },
  loginBtnText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '600',
    letterSpacing: 1,
  },
  error: {
    color: '#b5482b',
    fontSize: 13,
  },
  success: {
    color: '#2f6bd9',
    fontSize: 13,
  },
  footer: {
    marginTop: 'auto',
    alignItems: 'center',
    gap: 12,
  },
  registerBtn: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e5e5e5',
  },
  copyright: {
    fontSize: 11,
    color: '#999',
  },
});

function EyeClosedIcon() {
  return (
    <Svg viewBox="0 0 24 24" width={22} height={22} fill="none" stroke="#999" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24" />
      <Line x1="1" y1="1" x2="23" y2="23" />
    </Svg>
  );
}

function EyeOpenIcon() {
  return (
    <Svg viewBox="0 0 24 24" width={22} height={22} fill="none" stroke="#999" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" />
      <Circle cx="12" cy="12" r="3" />
    </Svg>
  );
}

function RegisterPlusIcon() {
  return (
    <Svg width={18} height={18} viewBox="0 0 24 24" fill="none">
      <Path d="M12 5V19M5 12H19" stroke="#666666" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}
