// src/components/Register.vue
﻿<script setup>
import { ref } from 'vue'
const props = defineProps({
  username: {
    type: String,
    default: '',
  },
  password: {
    type: String,
    default: '',
  },
  confirmPassword: {
    type: String,
    default: '',
  },
  loading: {
    type: Boolean,
    default: false,
  },
  error: {
    type: String,
    default: '',
  },
  status: {
    type: String,
    default: '',
  },
  canSubmit: {
    type: Boolean,
    default: false,
  },
})

const emit = defineEmits([
  'update:username',
  'update:password',
  'update:confirmPassword',
  'submit',
  'back',
])

const showPassword = ref(false)
const showConfirmPassword = ref(false)
</script>

<template>
  <div class="page">
    <h1 class="title">欢迎注册信聊</h1>

    <form class="form-container" @submit.prevent="emit('submit')">
      <div class="input-group">
        <input
          :value="props.username"
          type="text"
          placeholder="输入昵称"
          @input="emit('update:username', $event.target.value)"
        />
      </div>

      <div class="input-group">
        <input
          :value="props.password"
          :type="showPassword ? 'text' : 'password'"
          placeholder="输入信聊密码"
          @input="emit('update:password', $event.target.value)"
        />
        <button
          class="toggle-btn"
          type="button"
          @click="showPassword = !showPassword"
        >
          {{ showPassword ? '隐藏' : '显示' }}
        </button>
      </div>

      <div class="input-group">
        <input
          :value="props.confirmPassword"
          :type="showConfirmPassword ? 'text' : 'password'"
          placeholder="确认信聊密码"
          @input="emit('update:confirmPassword', $event.target.value)"
        />
        <button
          class="toggle-btn"
          type="button"
          @click="showConfirmPassword = !showConfirmPassword"
        >
          {{ showConfirmPassword ? '隐藏' : '显示' }}
        </button>
      </div>

      <label class="agreement">
        <input class="agreement-input" type="checkbox" checked />
        <span class="checkbox-circle"></span>
        <span class="agreement-text">
          已阅读并同意
          <a href="#">服务协议</a>
          和
          <a href="#">信聊隐私保护指引</a>
        </span>
      </label>

      <button class="register-btn" type="submit" :disabled="!props.canSubmit || props.loading">
        {{ props.loading ? '提交中...' : '立即注册' }}
      </button>

      <p v-if="props.error" class="message error">{{ props.error }}</p>
      <p v-else-if="props.status" class="message success">{{ props.status }}</p>

      <button class="back-link" type="button" @click="emit('back')">返回登录</button>
    </form>

    <footer class="footer">Copyright © 2025-2026 WebClass All Rights Reserved.</footer>
  </div>
</template>

<style scoped>
* {
  box-sizing: border-box;
}

.page {
  min-height: 100vh;
  height: 100vh;
  display: flex;
  flex-direction: column;
  background-color: #f0f2f5;
  padding-top: 80px;
  padding-top: calc(80px + env(safe-area-inset-top));
  box-sizing: border-box;
  overflow: hidden;
}

.title {
  text-align: center;
  font-size: 32px;
  font-weight: 400;
  color: #000;
  margin-bottom: 40px;
  letter-spacing: 1px;
}

.form-container {
  padding: 0 35px;
  display: flex;
  flex-direction: column;
  gap: 15px;
}

.input-group {
  background: #ffffff;
  border-radius: 10px;
  height: 52px;
  display: flex;
  align-items: center;
  padding: 0 15px;
  gap: 8px;
}

.input-group input {
  flex: 1;
  height: 100%;
  border: none;
  outline: none;
  background: transparent;
  font-size: 16px;
  color: #333;
}

.input-group input::placeholder {
  color: #ccc;
}

.toggle-btn {
  border: none;
  background: none;
  color: #4b6fa7;
  font-size: 12px;
  cursor: pointer;
  padding: 0 4px;
  white-space: nowrap;
}

.agreement {
  margin-top: 15px;
  display: flex;
  align-items: center;
  position: relative;
  font-size: 13px;
  color: #666;
  gap: 8px;
  cursor: pointer;
}

.agreement-input {
  margin: 0;
  opacity: 0;
  position: absolute;
  width: 1px;
  height: 1px;
  pointer-events: none;
}

.checkbox-circle {
  width: 18px;
  height: 18px;
  border: 1px solid #c0c4cc;
  border-radius: 50%;
  flex-shrink: 0;
  position: relative;
  pointer-events: none;
}

.agreement-input:checked + .checkbox-circle {
  border-color: #0099ff;
  background: #0099ff;
}

.agreement-input:checked + .checkbox-circle::after {
  content: '';
  position: absolute;
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #fff;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.agreement-text {
  line-height: 1.4;
}

.agreement a {
  color: #4b6fa7;
  text-decoration: none;
  margin: 0 2px;
}

.register-btn {
  margin-top: 25px;
  height: 50px;
  background-color: #0099ff;
  color: white;
  border: none;
  border-radius: 8px;
  font-size: 17px;
  font-weight: 600;
  width: 100%;
  cursor: pointer;
}

.register-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.register-btn:active {
  opacity: 0.8;
}

.message {
  font-size: 0.9rem;
  margin: 0;
}

.error {
  color: #b5482b;
}

.success {
  color: #2f6bd9;
}

.back-link {
  margin-top: 12px;
  background: none;
  border: none;
  color: #4b6fa7;
  font-size: 13px;
  cursor: pointer;
}

.footer {
  margin-top: auto;
  margin-bottom: 20px;
  text-align: center;
  font-size: 11px;
  color: #999;
  width: 100%;
  padding: 0 20px;
  line-height: 1.5;
}
</style>

// src/components/Register.tsx
import React, { useState } from 'react';
import {
  ActivityIndicator,
  Pressable,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Svg, { Circle, Line, Path } from 'react-native-svg';

type Props = {
  username: string;
  password: string;
  confirmPassword: string;
  loading: boolean;
  error: string;
  status: string;
  canSubmit: boolean;
  onUsernameChange: (value: string) => void;
  onPasswordChange: (value: string) => void;
  onConfirmPasswordChange: (value: string) => void;
  onSubmit: () => void;
  onBack: () => void;
};

export default function Register({
  username,
  password,
  confirmPassword,
  loading,
  error,
  status,
  canSubmit,
  onUsernameChange,
  onPasswordChange,
  onConfirmPasswordChange,
  onSubmit,
  onBack,
}: Props) {
  const insets = useSafeAreaInsets();
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);

  return (
    <View
      style={[
        styles.page,
        { paddingTop: insets.top + 40, paddingBottom: 20 + insets.bottom },
      ]}
    >
      <View style={styles.titleArea}>
        <Text style={styles.title}>欢迎注册信聊</Text>
      </View>

      <View style={styles.form}>
        <View style={styles.inputGroup}>
          <TextInput
            value={username}
            placeholder="输入昵称"
            placeholderTextColor="#c0c4cc"
            onChangeText={onUsernameChange}
            style={styles.input}
            autoCapitalize="none"
          />
        </View>

        <View style={styles.inputGroup}>
          <TextInput
            value={password}
            placeholder="输入信聊密码"
            placeholderTextColor="#c0c4cc"
            onChangeText={onPasswordChange}
            style={styles.input}
            autoCapitalize="none"
            secureTextEntry={!showPassword}
          />
          <Pressable onPress={() => setShowPassword((prev) => !prev)} style={styles.iconButton} hitSlop={8}>
            {showPassword ? <EyeOpenIcon /> : <EyeClosedIcon />}
          </Pressable>
        </View>

        <View style={styles.inputGroup}>
          <TextInput
            value={confirmPassword}
            placeholder="确认信聊密码"
            placeholderTextColor="#c0c4cc"
            onChangeText={onConfirmPasswordChange}
            style={styles.input}
            autoCapitalize="none"
            secureTextEntry={!showConfirm}
          />
          <Pressable onPress={() => setShowConfirm((prev) => !prev)} style={styles.iconButton} hitSlop={8}>
            {showConfirm ? <EyeOpenIcon /> : <EyeClosedIcon />}
          </Pressable>
        </View>

        <Pressable
          style={[styles.registerBtn, (!canSubmit || loading) && styles.registerBtnDisabled]}
          disabled={!canSubmit || loading}
          onPress={onSubmit}
        >
          {loading ? (
            <ActivityIndicator color="#fff" />
          ) : (
            <Text style={styles.registerText}>立即注册</Text>
          )}
        </Pressable>

        {error ? <Text style={styles.error}>{error}</Text> : null}
        {!error && status ? <Text style={styles.success}>{status}</Text> : null}

        <Pressable onPress={onBack}>
          <Text style={styles.backLink}>返回登录</Text>
        </Pressable>
      </View>

      <Text style={styles.footer}>Copyright © 2025-2026 WebClass</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#f0f2f5',
    paddingHorizontal: 24,
  },
  titleArea: {
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 40,
  },
  title: {
    fontSize: 24,
    fontWeight: '600',
    color: '#1a1a1a',
    letterSpacing: 1,
  },
  form: {
    gap: 16,
  },
  inputGroup: {
    backgroundColor: '#fff',
    borderRadius: 10,
    height: 52,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    position: 'relative',
  },
  input: {
    flex: 1,
    width: '100%',
    fontSize: 16,
    color: '#333',
    textAlign: 'center',
    paddingHorizontal: 36,
  },
  iconButton: {
    position: 'absolute',
    right: 14,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  registerBtn: {
    marginTop: 12,
    height: 50,
    borderRadius: 10,
    backgroundColor: '#0099ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  registerBtnDisabled: {
    opacity: 0.6,
  },
  registerText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '600',
  },
  error: {
    color: '#b5482b',
    fontSize: 13,
  },
  success: {
    color: '#2f6bd9',
    fontSize: 13,
  },
  backLink: {
    marginTop: 8,
    color: '#4b6fa7',
    fontSize: 13,
  },
  footer: {
    marginTop: 'auto',
    textAlign: 'center',
    fontSize: 11,
    color: '#999',
  },
});

function EyeClosedIcon() {
  return (
    <Svg viewBox="0 0 24 24" width={22} height={22} fill="none" stroke="#999" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24" />
      <Line x1="1" y1="1" x2="23" y2="23" />
    </Svg>
  );
}

function EyeOpenIcon() {
  return (
    <Svg viewBox="0 0 24 24" width={22} height={22} fill="none" stroke="#999" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" />
      <Circle cx="12" cy="12" r="3" />
    </Svg>
  );
}
